server {
    server_name celiblog.es www.celiblog.es;

    access_log /var/log/nginx/api.access.log combined;
    error_log /var/log/nginx/api.error.log;

    location / {
        proxy_pass http://192.168.0.13:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/celiblog.es/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/celiblog.es/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.celiblog.es) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = celiblog.es) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name celiblog.es www.celiblog.es;
    return 404; # managed by Certbot
}